name: Run WhatsApp Bot

on:
  workflow_dispatch: 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install Virtual Display & Browser packages
        run: sudo apt-get update && sudo apt-get install -y xvfb libgbm-dev libnss3 libatk-bridge2.0-0 libgtk-3-0

      - name: Start WhatsApp Bot with Virtual Monitor
        run: xvfb-run --auto-servernum node index.js
